project:
  type: website
  output-dir: docs
  resources:
    - CV2026.pdf

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    